<?php

use App\Models\MovieModel;
use App\Models\Utils;

Encore\Admin\Form::forget(['map', 'editor']);

// open the file "demosaved.csv" for writing
$class_name = 'S.2';
$file = fopen($class_name . '.csv', 'w');
$names_1 = 'AFAYO DEVIS,AKAMEZELE HAMFREY,AKAMUMPA REHANNAH,ALIKOBA RACHEAL,ALINTUSA ZION,ANYANGO JUSTINE PRAISE,ASIIMWE CHRISTINE PEACE,BABIRYE BABRA,BABIRYE CATHERINE,BABIRYE FROLENCE,BABIRYE HAJIRAH,BAKIMANYIRE SELEVANO,BALIKOWA JOEL,BALIMA HOPE,BAMUSUBIRE MEASRCH,BASIBA EZRA,BASOGA PRECIOUS,BATALE EDGER T,BULIDHA HAMAN,BYALERO JOSEPH,CHEPTOYEK SSHIFA ROSE,DAKA KENETH,DIIRO TIMOTHY,GANDI JOSHUA,GWITABINGI SHADIA,IBINGA LIVINGSTONE,IKESA SHARON,IMPINDI IMMACULATE,IMURAN FAHAD,ISABIRYE BENARD,ISABIRYE CONSTANT,ISABIRYE FARAGI,ISABIRYE ISAAC,ISABIRYE JOVAN,ISIIGA ANGELLA GRACE,ISOOBA AMBROSE,ISOOBA IRENE,ISOOBA TABISA,KABI EDRINE,KABWIRE GEOFREY,KAIMA IMMACULATE,KALIREKU ROMANO,KAMANYA GEOFREY ,KAMPI MONIC,KAMUKAMA BELIEVIN,KANEENE ERIC,KANYAGO SHIVAN MARY,KAPSANDUI JESSE,KASIMU TEPHERO,KASIRYE STEVEN,KAUMA SHANITAH,KAVUNANA MARGRET,KAWALA JACKLINE,KAWANGUZI EMMANUEL,KIBOGOYI JUDITH,KIIGE YEEKO,KIIGE YOKOLAMU,KIIZA SHADIA,KIIZA SHADIA,KIRABO AGATHA AGNES,KIRABO JOVIA ROBINAH,KIRABO SARAH,KIRIGOOLA SOLOMON PASSY,KISAKYE DIVINE,KISAKYE ELIZABETH,KIWANUKA JORAMU,KONSO ROSE,KULATA JORAM,KUTEGANA DENIS,KWAGALA DOREEN NABEETA,KWAGALA VERONICA,KYAIRO KENNETH,KYAZIKE MARY,KYOBULA SHIVAN,LUBOGO DAVID,LUBOGO KENNETH,LUGHATA JONAH,LUYUYO LATIFU MUSOOKO,MALIJO DEVIS,MALUSHA MARK W,MASAU CALEB JONATHAN,MASSA PIUS,MATOVU DAWN,MBEIZA DAPHINE,MBWALI JULIET,MBWALI SHARIAT,MPINDI IMMACLATE ,MUJA BRIDGET PEACE,MUKAMA CHALRES,MUKAMA JAMIRU ,MUKANZA BEATRICE,MUKEBEZI DAPHINE,MUKISA ANDREW,MUKISA ERIA,MUKISA YOWASI,MULEDHU DANIEL,MUMBOGWE HILLARY AGGREY,MUSASIZI EVANS JOSHUA,MUSENERO SARAH,MUSUBIKA PHIONA,MUSUBIKA PROSSY,MUSUBIKA SHANATI,MUSUMBAKYAYI ROSEMARY,MUTESI HALIMAH,MUTESI RACHEAL,MUTYABULE AMBROSE,MUWAGA CHARLES,MUWAYA BRIAN,MUYINGO EDRINE,MUYINGO MARK,MUYODI WILBERFORCE,MWESIGWA SHAFIK,NAAVA ANGEL DEBORAH,NABAIGWA ANNASTA MACKLINE,NABIRYE ALMOND JOY,NABIRYE VIOLA,NABIRYO BRENDA ,NABULUMBA IRENE,NAFUNAH MERCY KHAINZA,NAIKOMBA ROSE,NAKADAMA PERINAH,NAKALIMO PHIONA,NAKAMANYA AISHA,NAKIRYA PATIENCE,NAKIYEMBA MARIAM ,NALUBEGA OLIVIA,NAMBOIRA BEATRICE,NAMUGABWE SHARON,NAMUHANGA GIFT,NAMUKISA MERCY TENDO,NAMUKOSE ESTHER,NAMUKOSE JOY,NAMUKOSE JUDITH,NAMUKOSE LILIAN,NAMULEMO MARIAM,NAMULUTA MANJERI,NAMUNANA DORCUS,NAMUSWA LETICIA JOYCE,NAMUWANGA HANIFAH,NANGOBI DAPINE,NANGOBI KOLOSI,NANGOBI MERCY,NANGOBI SHARON,NANYANGA SHADIA,NANZALA MOUREEN VIOLA,NDHALAMBI JOSHUA DERRICK,NKOLWA JAMES JOET,OJOGOLO BASWIRI,OKOTH MARK ,OPIO ASHIRAF,PEESA SAMSON,REAGAN KELVIN WANDERA,SAAHE SHAFIKI,SAYUNI REBECCA,SENYENTA ISIMA,SIMAIRIRE SOLOMON,SOOMA JANET,SOOMA JULIET,SOOTO FATUHU,TAFUMBA ZUBEDAH,TALUNGA HADIJJAH,TAZUBA TIMOTHY,TIBANONE GIDEON,TIBAZIKANWA MARTHA ,TIBITONDWA SHAKIRAH,TUMUGONZE EDITH,TUSABOMU BRIDGET,TUSUBIRA GLORIA,TUSUBIRA GONZA,TUSUBIRA LEAH,TUSUBIRA MARIAM,TWESIMYE ANGEL,WAFUBA NOEL,WAISWA ANIFU,WAISWA JOSHUA,WAISWA JUMA,WAISWA WILLY,WAMBI ROBERT,WANDUKWA DAN,WANYENYA PAULINE';
$names = explode(',', $names_1);

fputcsv($file, []);
$data = [];
foreach ($names as $key => $name) {
    $first_and_last_name = explode(' ', $name);
    $first_name = $first_and_last_name[0];
    if (isset($first_and_last_name[0]) && isset($first_and_last_name[1])) {
        $first_name = $first_and_last_name[0];
        $last_name = $first_and_last_name[1];
    } else {
        die('Last name not found');
    }
    if (isset($first_and_last_name[2])) {
        $last_name .= ' ' . $first_and_last_name[2];
    }
    $id = $class_name . '-' . $first_name . '-' . $last_name;
    $id = strtoupper(str_replace(' ', '-', $id));
    $id = str_replace(' ', '-', $id);
    $data[] = array($id, $first_name, $last_name);
}
 
// save each row of the data
foreach ($data as $row) {
    fputcsv($file, $row);
}

// Close the file
fclose($file);

die("done");

//Utils::system_boot();
/* foreach (MovieModel::all() as $key => $value) {
    $value->title = str_replace('/', '', $value->title);
    $value->save(); 
} */

/* try {
    $u = \App\Models\User::where('email', 'mubahood360@gmail.com')->first();
    $code = rand(100000, 999999);
    $u->secret_code = $code;
    $u->save();

    $mail_body = <<<EOD
    <p>Dear {$u->name},</p>
    <p>Your password reset code is <b>$code</b></p>
    <p>Thank you.</p>
    EOD;

    $data['email'] = $u->email;
    $date = date('Y-m-d');
    $data['subject'] = "Password Reset Code - " . env('APP_NAME');
    $data['body'] = $mail_body;
    $data['data'] = $data['body'];
    $data['name'] = $u->name;
    try {
        Utils::mail_sender($data);
        dd("success 1");
    } catch (\Throwable $th) {
        dd("failed because 1 " . $th->getMessage());
        return Utils::error($th->getMessage());
    }
} catch (\Exception $e) {
    dd("failed because 2 " . $e->getMessage());
    return Utils::error($e->getMessage());
}
die("done"); */
